USE mysql;

CREATE TABLE TENANT (
    ID VARCHAR(255) NOT NULL UNIQUE,
    ACCOUNTNAME VARCHAR(255) NOT NULL,
    KIND VARCHAR(255) NOT NULL,
    NAMESPACE VARCHAR(255) NOT NULL,
    HOSTNAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
